name: 🗜️ PNG Compression

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  
jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zopfli
          
      - name: Compress PNGs
        run: |
          echo "🖼️  Compressing PNGs..."
          find png/ -iname "*.png" -print0 | xargs -0 -P 4 -I{} sh -c 'echo "Compressing {}"; zopflipng -y {} {}' || true
          
      - name: Load to GitHub
        run: |-
          git diff
          git config --global user.name 'drag0n141-bot[bot]'
          git config --global user.email '143080396+drag0n141-bot[bot]@users.noreply.github.com'
          git add -A
          git commit -m ":clamp: Compresses PNGs" || exit 0
          git pull --ff-only
          git push
